### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getElementsByClassName' of undefined

### ISSUE THREAD

**Issue by GeertJohan** [ruhatch/sublime-panes#1]
Thanks for creating this package, it's pretty awesome!
1. Open a file in preview (without editing)
2. Close with ctrl+w

**Atom Version**: 1.0.11
**System**: Ubuntu 15.04
**Thrown From**: [sublime-panes](https://github.com/ruhatch/sublime-panes) package, v0.2.5
### Stack Trace

Uncaught TypeError: Cannot read property 'getElementsByClassName' of undefined

```
At /home/geertjohan/.atom/packages/sublime-panes/lib/sublime-panes.coffee:58

TypeError: Cannot read property 'getElementsByClassName' of undefined
  at Object.module.exports.SublimePanes.catchItem (/home/geertjohan/.atom/packages/sublime-panes/lib/sublime-panes.coffee:58:5)
  at /home/geertjohan/.atom/packages/sublime-panes/lib/sublime-panes.coffee:52:68
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:250:22)
  at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:392:16)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:466:16)
  at Pane.module.exports.Pane.destroyActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:443:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:617:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/usr/share/atom/resources/app.asar/src/workspace.js:656:21)
  at atom-workspace.atom.commands.add.core:close (/usr/share/atom/resources/app.asar/src/workspace-element.js:290:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -1:27.9.0 settings-view:open (atom-text-editor.editor.is-focused)
  4x -1:23.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:23 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:close (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "/home/geertjohan"
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
color-picker, v2.0.11
file-icons, v1.6.9
go-plus, v3.5.1
go-rename, v0.3.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-protobuf, v0.5.0
minimap, v4.13.2
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
project-manager, v2.4.0
stash-tabs, v0.1.0
sublime-panes, v0.2.5

# Dev
No dev packages
```

**Comment by lukeed** [comment]
+1, and my package list is far shorter: 4 including sublime-panes

**Comment by jhiemer** [comment]
+1

**Comment by tonypee** [comment]
seems sublime-tabs is broken... makes using atom really hard as its so essential! please fix!

**Comment by tonypee** [comment]
seems that it is in the core now: 
1. Open the Settings View (Cmd+, or Ctrl+,)
2. Go to the Packages sidebar
3. Search for "Tabs"
4. Click the Tabs package's Settings button
5. Find the "Use Preview Tabs" option and enable it
6. :tada:

**Comment by hvmonteiro** [comment]
This happens also by opening "Settings" on a tab, switch to a different tab, and back again to "Settings" tab.
The plugin needs to check whether the tab is an opening file or not. OR if tab is an "internal" tab/window.

Cheers
