### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroyItem' of undefined

### ISSUE THREAD

**Issue by Janee** [ruhatch/sublime-panes#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [sublime-panes](https://github.com/ruhatch/sublime-panes) package, v0.2.5
### Stack Trace

Uncaught TypeError: Cannot read property 'destroyItem' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/q/q.js:128

TypeError: Cannot read property 'destroyItem' of undefined
  at Object.module.exports.SublimePanes.cleanUp (/home/diana/.atom/packages/sublime-panes/lib/sublime-panes.coffee:76:11)
  at Object.module.exports.SublimePanes.registerInterest (/home/diana/.atom/packages/sublime-panes/lib/sublime-panes.coffee:50:6)
  at /home/diana/.atom/packages/sublime-panes/lib/sublime-panes.coffee:25:61
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:352:27)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:339:26
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app.asar/src/pane.js:345:20)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:313:14)
  at /usr/share/atom/resources/app.asar/src/workspace.js:489:16
  at _fulfilled (/usr/share/atom/resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app.asar/node_modules/q/q.js:756:13)
  at /usr/share/atom/resources/app.asar/node_modules/q/q.js:564:44
  at flush (/usr/share/atom/resources/app.asar/node_modules/q/q.js:110:17)
  at doNTCallback0 (node.js:416:9)
  at process._tickCallback (node.js:345:13)

```
### Commands

```
     -0:05.8.0 command-palette:toggle (atom-text-editor.editor.vim-mode.visual-mode.is-focused)
     -0:02.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 git-plus:add-all-and-commit (atom-text-editor.editor.vim-mode.visual-mode)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
aligner-ruby, v1.4.0
atom-beautify, v0.28.14
autocomplete-ruby, v0.1.0
color-picker, v2.0.13
git-plus, v5.4.7
linter, v1.8.1
linter-ruby, v1.2.0
ruby-block, v0.3.5
spotify-linux, v0.3.2
sublime-panes, v0.2.5
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by ozak** [comment]
@Janee was this resolved somehow? I am getting the same error when ``Cmd-K + right``.

**Comment by Janee** [comment]
@ozak Just updating atom
